
* ../v0.0/word_frequency.js
a Javascript file, with 72934 lines of form:
localStorage.setItem("a", "11");
localStorage.setItem("akaṇṭaka", "5");

From Marcis Gasuns. Adapted from work of Oliver Hellwig (sp?).

* word_frequency.txt
a 1
akaRwaka 5
SLP1 transliteration
python word_frequency.py ../v0.0/word_frequency.js word_frequency.txt

* word_frequency_adj.txt  (Jul 20, 2017)
  There are duplicate words in word_frequency.txt, with different
  frequency counts.
  This step removes the duplicates, and uses the LARGEST of the
   word-frequencies when there are duplicates.
python word_frequency_adj.py word_frequency.txt word_frequency_adj.txt  word_frequency_dups.txt
72933 read from word_frequency.txt
4932 records written to word_frequency_dups.txt
67050 records written to word_frequency_adj.txt

As a check:
python word_frequency_adj.py word_frequency_adj.txt word_frequency_adj_adj.txt  word_frequency_adj_dups.txt
Result is that word_frequency_adj_adj.txt is same as word_frequency_adj.txt,
  and word_frequency_adj_dups.txt is empty.  This is as expected.
