<?php
/*
 getword_list_0.1.php  
 Variant of getword_list_1.0.php of fetching_v0.3b.
 Designed to work with list-0.2s.html
  06-01-2017. based on apidev/getword_xml.php
  'key' is treated as a comma-delimited list of keys
  Retrieves info for a given headword; retrieves from web/sqlite/<dict>.xml
  Enhancement:  retrieve multiple headwords
  Enhancement:  retrieve based on normalized spelling
  06-02-2017. In this version, the variants are generated by php, rather
        than being pregenerated by javascript
  06-05-2017. Compute variants with SLP
*/
require_once('getword_list_1.0_main.php');
$ans = getword_list_processone(); // Gets arguments from $_REQUEST
header("Access-Control-Allow-Origin: *");
header('content-type: application/json; charset=utf-8');

$json = json_encode($ans);
if (isset($_REQUEST['callback'])) {
 $callback = $_REQUEST['callback'];
 // Validate the JSONP callback before reflecting it: an unrestricted value is
 // a reflected-XSS / JSONP-injection vector. Mirrors the guard in
 // csl-websanlexicon webtc/getword.php (issue #27).
 if (!preg_match('/^[A-Za-z_$][A-Za-z0-9_$.]{0,127}$/',$callback)) {
  header('content-type: text/plain; charset=utf-8');
  http_response_code(400);
  echo "invalid callback";
  exit;
 }
 // htmlspecialchars is a no-op on the whitelisted callback, but it is the
 // sanitizer Semgrep's echoed-request rule recognises (defense-in-depth over
 // the preg_match whitelist, which is the real JSONP control).
 echo htmlspecialchars($callback) . "($json)";
}else {
 echo $json;
}

?>
