
v0.2a   computes variants only with the php algorithm,
  Assume input key is HK, and
  compute variants in SLP1.
  Reason: more efficient

* ../v0.0/word_frequency.js
a Javascript file, with 72934 lines of form:
localStorage.setItem("a", "11");
localStorage.setItem("akaṇṭaka", "5");

From Marcis Gasuns. Adapted from work of Oliver Hellwig (sp?).

* word_frequency.txt
a 1
akaRwaka 5
SLP1 transliteration
python word_frequency.py ../v0.0/word_frequency.js word_frequency.txt

* Documentation of method
getword_list_1.0.php
 keyparmin is what user input: 
   Assumed to be one of (a) Devanagari, (b) IAST, (c) HK.
 Also use 'dict' and 'output' parameters when generating results.
 keysin0 is list of alternates:
    keysin0 = generate_alternates($keyparmin)
      a) wordin1 = convert_nonascii(keyparmin):   wordin1 is supposed to be HK.
         -- if keyparmin consists wholly of letters a-zA-Z, then wordin1=keyparmin
         -- Otherwise, 
            -- 1. Let wordin1 be the transcoding of keyparmin from devanagari to SLP1;
               2. If wordin1 is different than keyparmin (i.e., if keyparmin has devanagari),
                  then further transcode wordin1 to HK, and return wordin1
            -- We now know that keyparmin (a) has non-alphabetical characters and
               (b) does not have Devanagari characters.  Assume those non-alphabetical
               characters are present due to IAST diacritics (i.e., the user has entered
               IAST).  
               1. Change and 'w,W' in keyparmin to 'v':
                  Reason: w,W are not in HK alphabet; BUT are in SLP1 alphabet.
                  NOTE: Need to check if any other letters are similar
               2. Let wordin1 be the transcoding of keyparmin from IAST to SLP1
                  If there is no difference between wordin1 and keyparmin, then return.
                  Otherwise, further transcode wordin1 from SLP1 to HK
      b) Construct a  Simple_Search instance object from wordin1 [see below]
         The 'keysin' attribute of this object is a list of SLP1 spellings.
         This list is  the value returned by generate_alternates($keyparmin).
         (keyin0 of Simple_Search is wordin1)
         - alternates = generate_hkalternates(keyin0)
           (wordin = keyin0)
          b1. wordin = correcthk(wordin)
            ii,ee -> i;   uu,oo -> u; aa -> a; chh -> ch; E -> ai;
            O -> au;
	    rXX -> rX    [  ODD: undouble consonant after 'r' Why?]
            R^i, RR^i -> R  [ vocalic R ]
          b2.  split wordin into sequence of letters.
            For each letter x, make a list of alternate letters:
              if x = f -> [p,ph]  
              otherwise [x]
          b3. 
 Simple_Search constructor.

 For each key in keysin0:
  
